# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = '/wreckthisbeach/*'
  to = '/.netlify/functions/:splat'
  status = 200

